name: QA Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest --alluredir=reports/allure-results || true
        allure generate reports/allure-results -o reports/html --clean

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports/html

    - name: Notify Slack
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Testes executados! Veja o relatório."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
